/**
 * Assertion strategy used by canvas and preview asserters.
 */
export type AssertStrategy =
  | 'text-content'
  | 'visibility'
  | 'attribute'
  | 'css-property'
  | 'class-contains'
  | 'not-exists';

/**
 * How the property-setter interacts with a Studio property field.
 */
export type InputType = 'text' | 'toggle' | 'dropdown' | 'binding' | 'combined';

/**
 * Whether preview is tested per-case or in a single batched session.
 */
export type PreviewMode = 'individual' | 'batched';

/**
 * A single assertion definition — used for both canvas and preview.
 */
export interface AssertDefinition {
  strategy: AssertStrategy;
  xpath: string;
  expected?: string | boolean | number;
  attribute?: string;
  cssProperty?: string;
}

/**
 * A single test case from {widget}-test-cases.json.
 */
export interface TestCase {
  id: string;
  section: string;
  testCase: string;
  input: string | boolean | number | Record<string, unknown>;
  inputType: InputType;
  canvasAssert: AssertDefinition;
  previewAssert: AssertDefinition;
  previewMode: PreviewMode;
  cleanup?: {
    section: string;
    input: string | boolean | number;
    inputType: InputType;
  } | null;
}

/**
 * A Studio variable row in `{widget}-test-cases.json` → `variables`, created before tests run.
 * For binding test cases, `name` must match the segment in `Variables.<name>.dataSet.dataValue`,
 * and `type` / `defaultValue` must match what Studio needs on the Properties tab (Type + JSON dataValue).
 */
export interface VariableDefinition {
  name: string;
  /**
   * Model variable **Type** in Studio (String, Boolean, List, Number, …).
   */
  type: 'string' | 'number' | 'boolean' | 'list';
  /**
   * **Data value** (JSON `dataValue` in Studio) — same value bound via `Variables.<name>.dataSet.dataValue`.
   */
  defaultValue: string;
  /**
   * Studio "New variable" category (Model, Service, …). Only **Model** is automated in `variable-manager.ts`.
   * Defaults to `"Model"` when omitted / when generated by `generate-test-cases.ts`.
   */
  studioCategory?: string;
}

/**
 * Test cases file structure.
 */
export interface TestCasesFile {
  widget: string;
  totalTestCases: number;
  variables?: VariableDefinition[];
  testCases: TestCase[];
}

/**
 * A property section entry in the widget config.
 */
export interface PropertySection {
  xpath: string;
  interactionType: InputType;
}

/**
 * Widget configuration from {widget}.config.json.
 */
export interface WidgetConfig {
  widget: string;
  tag: string;
  prefix: string;
  componentPanelId: string;
  defaultName: string;
  canvasXPaths: Record<string, string>;
  previewXPaths: Record<string, string>;
  propertiesPanel: Record<string, Record<string, PropertySection>>;
}

/**
 * Result of a single test case execution.
 */
export interface TestResult {
  id: string;
  testCase: string;
  section: string;
  canvasResult: 'pass' | 'fail' | 'skip';
  previewResult: 'pass' | 'fail' | 'skip';
  canvasError?: string;
  previewError?: string;
  durationMs: number;
}

/**
 * Full test report structure.
 */
export interface TestReport {
  widget: string;
  timestamp: string;
  totalCases: number;
  passed: number;
  failed: number;
  skipped: number;
  durationMs: number;
  results: TestResult[];
}
